name: capstone-tco
services:
  web-fe:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: TCO-DMS-FE
    ports:
      - "5173:80"

  server-be:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: TCO-DMS-BE
    ports:
      - "8080:8080"

  clamav:
    image: clamav/clamav:stable
    container_name: TCO-DMS-Clamav
    ports:
      - "3310:3310"

  ai-service:
    build:
      context: ./AI
      dockerfile: Dockerfile
    container_name: TCO-DMS-AI
    ports:
      - "8000:8000"
#    volumes:
#      - clamav:/var/lib/clamav
#    platform: linux/amd64
#
#volumes:
#  clamav: