server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # security headers
	add_header X-Frame-Options "SAMEORIGIN" always;
	add_header X-Content-Type-Options "nosniff" always;
	add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    charset utf-8;
	gzip on;
	gzip_types
		text/plain
		text/css
		text/javascript
        text/xml
        image/svg+xml
        application/xml
        application/javascript
		application/json;

    # optimize caching for static assets
    location ~* \.(js|css|png|jpg|jpeg|svg|gif|ico|woff|woff2|ttf|eot)$ {
        expires 7d;
        access_log off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}