spring.application.name=HCLCapstoneBE
server.port=8080

# ?? Database (Supabase - Transaction Pooler) ?????????????
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.pkbwoortbtsvbcggybia
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.password=HCLCapstone123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.hikari.data-source-properties.prepareThreshold=0


# ?? JPA ??????????????????????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ?? JWT ??????????????????????????????????????????????????
jwt.secret=hcl-capstone-super-secret-jwt-key-2024
jwt.expiration=86400000

# ?? File upload ??????????????????????????????????????????
file.upload-dir=uploads/