"""
Issue #309 -- builds a real filled multi-page text-native PDF sample:
converts an already-filled balance-sheet DOCX (samples/en_balance_sheet/
Balance-sheet-template-FILLED-300.docx, generated by _fill_templates.py)
through the SAME production conversion function main.py's own .docx
upload branch uses (file_routing.convert_docx_to_pdf_bytes), so the
result is exactly what a real user's .docx upload would produce as a
.pdf, not a hand-rolled approximation. Real, confirmed multi-page: the
resulting PDF spans 4 pages with Total Assets/Total Liabilities landing
on pages 2/3, not page 1 -- the exact "totals not on page 1" scenario
pipeline.py's own _run_text_native_path comments already describe as a
real historical bug class (#283), previously only ever verified against
BLANK real PDF templates with no actual values to redact.

Not part of production's import chain -- this only calls an already-
production function against a local sample file, no new dependency.
"""

import sys

from file_routing import convert_docx_to_pdf_bytes


def make_multipage_pdf(docx_path: str, pdf_path: str) -> None:
    with open(docx_path, "rb") as f:
        docx_bytes = f.read()
    pdf_bytes = convert_docx_to_pdf_bytes(docx_bytes)
    with open(pdf_path, "wb") as f:
        f.write(pdf_bytes)


if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else "samples/en_balance_sheet/Balance-sheet-template-FILLED-300.docx"
    dst = sys.argv[2] if len(sys.argv) > 2 else "samples/en_balance_sheet/Balance-sheet-template-FILLED-300.pdf"
    make_multipage_pdf(src, dst)
    print(f"saved {dst}")
