"""
Real accuracy measurement for Module 2 extraction, against the synthetic
filled validation batch generated by _fill_templates.py.

Ground truth comes from re-running the same deterministic (seed, template)
pairs used to generate the batch -- fill_docx() returns exactly which value
it inserted for which field, so there's no need to hand-annotate anything.
This rewrites the already-committed -FILLED files with byte-identical
content (same seed + same source = same output), it does not change them.
"""

import glob
from pathlib import Path

from _fill_templates import fill_docx
from module2_text_extraction import extract_fields

SCALAR_FIELDS = {"name", "address"}
LIST_FIELDS = {"cccd", "phone", "salary"}


def build_manifest() -> list[tuple[str, str, int]]:
    """Reconstruct the exact (src, dst, seed) triples used for the batch --
    same glob order, same seed sequence, as the original generation run."""
    manifest = []
    seed = 100

    contract_srcs = [p for p in sorted(glob.glob("samples/contract/*.docx")) if "FILLED" not in p]
    for src in contract_srcs:
        dst = f"samples/contract/{Path(src).stem}-FILLED.docx"
        manifest.append((src, dst, seed))
        seed += 1

    payslip_srcs = [p for p in sorted(glob.glob("samples/pay_slip/*.docx")) if "FILLED" not in p]
    for src in payslip_srcs:
        for rep in range(3):
            dst = f"samples/pay_slip/{Path(src).stem}-FILLED-{rep + 1}.docx"
            manifest.append((src, dst, seed))
            seed += 1

    return manifest


def score() -> None:
    manifest = build_manifest()
    totals = {f: 0 for f in SCALAR_FIELDS | LIST_FIELDS}
    correct = {f: 0 for f in SCALAR_FIELDS | LIST_FIELDS}
    misses = []

    for src, dst, seed in manifest:
        _, ground_truth = fill_docx(src, dst, seed=seed)
        extracted = extract_fields(dst)["fields"]

        for field in SCALAR_FIELDS:
            gt_values = set(ground_truth.get(field, []))
            if not gt_values:
                continue
            totals[field] += 1
            value = extracted.get(field)
            if value is not None and value in gt_values:
                correct[field] += 1
            else:
                misses.append((dst, field, sorted(gt_values), value))

        for field in LIST_FIELDS:
            gt_values = ground_truth.get(field, [])
            if not gt_values:
                continue
            extracted_set = set(extracted.get(field) or [])
            for v in gt_values:
                totals[field] += 1
                if v in extracted_set:
                    correct[field] += 1
                else:
                    misses.append((dst, field, [v], sorted(extracted_set)))

    with open("accuracy_report.txt", "w", encoding="utf-8") as out:
        out.write(f"Documents scored: {len(manifest)}\n\n")
        out.write("Per-field accuracy (correct / total ground-truth values):\n")
        overall_correct = overall_total = 0
        for field in ("name", "address", "cccd", "phone", "salary"):
            t, c = totals[field], correct[field]
            pct = f"{100 * c / t:.1f}%" if t else "n/a (no ground truth)"
            out.write(f"  {field:8s}: {c:3d} / {t:3d}  ({pct})\n")
            overall_correct += c
            overall_total += t
        overall_pct = f"{100 * overall_correct / overall_total:.1f}%" if overall_total else "n/a"
        out.write(f"\nOverall: {overall_correct} / {overall_total}  ({overall_pct})\n")

        out.write(f"\nMisses ({len(misses)}):\n")
        for dst, field, expected, got in misses:
            out.write(f"  {dst}\n    field={field} expected={expected!r} got={got!r}\n")

    print("saved accuracy_report.txt")


if __name__ == "__main__":
    score()
