"""
Real accuracy measurement for Module 2 extraction (English, text-native
path), against the synthetic filled validation batch generated by
_fill_templates.py.

Ground truth comes from re-running the same deterministic (seed, template)
pairs used to generate the batch -- fill_docx() returns exactly which value
it inserted for which field, so there's no need to hand-annotate anything.
This rewrites the already-committed -FILLED files with byte-identical
content (same seed + same source = same output), it does not change them.
"""

from _fill_templates import fill_docx
from field_extraction_en import parse_currency_amount
from module2_text_extraction import extract_fields

SCALAR_FIELDS = {"name", "address", "bsb", "account_number"}
LIST_FIELDS = {"abn", "salary"}

CONTRACT_SRC = "samples/en_contract/part-time-employment-contract.docx"
PAYSLIP_SRC = "samples/en_pay_slip/Pay-slip-template-sts.docx"
REPS_PER_TEMPLATE = 18


def build_manifest() -> list[tuple[str, str, int]]:
    """(src, dst, seed) triples -- 18 reps of the one vetted contract
    template, 18 reps of the one vetted payslip template. Both templates
    were screened against field_extraction_en.py's actual LABEL_PATTERNS
    before being chosen; every other downloaded candidate's placeholders
    didn't sit in a colon-anchored label line and was dropped rather than
    special-cased (see docs/superpowers/specs/2026-08-12-en-validation-
    corpus-benchmark-design.md, Decision 3)."""
    manifest = []
    seed = 100

    for _ in range(REPS_PER_TEMPLATE):
        dst = f"samples/en_contract/part-time-employment-contract-FILLED-{seed}.docx"
        manifest.append((CONTRACT_SRC, dst, seed))
        seed += 1

    for _ in range(REPS_PER_TEMPLATE):
        dst = f"samples/en_pay_slip/Pay-slip-template-sts-FILLED-{seed}.docx"
        manifest.append((PAYSLIP_SRC, dst, seed))
        seed += 1

    return manifest


def score() -> None:
    manifest = build_manifest()
    totals = {f: 0 for f in SCALAR_FIELDS | LIST_FIELDS}
    correct = {f: 0 for f in SCALAR_FIELDS | LIST_FIELDS}
    income_total = income_correct = 0
    misses = []

    for src, dst, seed in manifest:
        _, ground_truth = fill_docx(src, dst, seed=seed)
        extracted = extract_fields(dst)["fields"]

        for field in SCALAR_FIELDS:
            gt_values = set(ground_truth.get(field, []))
            if not gt_values:
                continue
            totals[field] += 1
            value = extracted.get(field)
            if value is not None and value in gt_values:
                correct[field] += 1
            else:
                misses.append((dst, field, sorted(gt_values), value))

        for field in LIST_FIELDS:
            gt_values = ground_truth.get(field, [])
            if not gt_values:
                continue
            extracted_set = set(extracted.get(field) or [])
            for v in gt_values:
                totals[field] += 1
                if v in extracted_set:
                    correct[field] += 1
                else:
                    misses.append((dst, field, [v], sorted(extracted_set)))

        gt_income = ground_truth.get("income")
        if gt_income:
            income_total += 1
            expected = parse_currency_amount(gt_income[0])
            expected_basis = ground_truth["income_basis"][0]
            got = extracted.get("income")
            got_basis = extracted.get("income_basis")
            if got is not None and abs(got - expected) < 0.01 and got_basis == expected_basis:
                income_correct += 1
            else:
                misses.append((dst, "income", [gt_income[0]], (got, got_basis)))

    with open("accuracy_report.txt", "w", encoding="utf-8") as out:
        out.write(f"Documents scored: {len(manifest)}\n\n")
        out.write("Per-field accuracy (correct / total ground-truth values):\n")
        overall_correct = overall_total = 0
        for field in ("name", "address", "bsb", "account_number", "abn", "salary"):
            t, c = totals[field], correct[field]
            pct = f"{100 * c / t:.1f}%" if t else "n/a (no ground truth)"
            out.write(f"  {field:15s}: {c:3d} / {t:3d}  ({pct})\n")
            overall_correct += c
            overall_total += t
        income_pct = f"{100 * income_correct / income_total:.1f}%" if income_total else "n/a"
        out.write(f"  {'income':15s}: {income_correct:3d} / {income_total:3d}  ({income_pct})\n")
        overall_correct += income_correct
        overall_total += income_total
        overall_pct = f"{100 * overall_correct / overall_total:.1f}%" if overall_total else "n/a"
        out.write(f"\nOverall: {overall_correct} / {overall_total}  ({overall_pct})\n")

        out.write(f"\nMisses ({len(misses)}):\n")
        for dst, field, expected, got in misses:
            out.write(f"  {dst}\n    field={field} expected={expected!r} got={got!r}\n")

    print("saved accuracy_report.txt")


if __name__ == "__main__":
    score()
